/*
 * Go Clean Template API
 *
 * Using a translation service as an example
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type V1DoTranslateRequest struct {
	Destination string `json:"destination"`

	Original string `json:"original"`

	Source string `json:"source"`
}
