/*
 * Go Clean Template API
 *
 * Using a translation service as an example
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type V1HistoryResponse struct {
	History []EntityTranslation `json:"history,omitempty"`
}
