// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: docs/proto/v1/translation.history.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for GetHistory.
type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_docs_proto_v1_translation_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_translation_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_translation_history_proto_rawDescGZIP(), []int{0}
}

// Response message for GetHistory.
type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	History       []*TranslationHistory  `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_docs_proto_v1_translation_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_translation_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_translation_history_proto_rawDescGZIP(), []int{1}
}

func (x *GetHistoryResponse) GetHistory() []*TranslationHistory {
	if x != nil {
		return x.History
	}
	return nil
}

// Translation message structure.
type TranslationHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Original      string                 `protobuf:"bytes,3,opt,name=original,proto3" json:"original,omitempty"`
	Translation   string                 `protobuf:"bytes,4,opt,name=translation,proto3" json:"translation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslationHistory) Reset() {
	*x = TranslationHistory{}
	mi := &file_docs_proto_v1_translation_history_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslationHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationHistory) ProtoMessage() {}

func (x *TranslationHistory) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_translation_history_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationHistory.ProtoReflect.Descriptor instead.
func (*TranslationHistory) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_translation_history_proto_rawDescGZIP(), []int{2}
}

func (x *TranslationHistory) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *TranslationHistory) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *TranslationHistory) GetOriginal() string {
	if x != nil {
		return x.Original
	}
	return ""
}

func (x *TranslationHistory) GetTranslation() string {
	if x != nil {
		return x.Translation
	}
	return ""
}

var File_docs_proto_v1_translation_history_proto protoreflect.FileDescriptor

const file_docs_proto_v1_translation_history_proto_rawDesc = "" +
	"\n" +
	"'docs/proto/v1/translation.history.proto\x12\agrpc.v1\"\x13\n" +
	"\x11GetHistoryRequest\"K\n" +
	"\x12GetHistoryResponse\x125\n" +
	"\ahistory\x18\x01 \x03(\v2\x1b.grpc.v1.TranslationHistoryR\ahistory\"\x8c\x01\n" +
	"\x12TranslationHistory\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x1a\n" +
	"\boriginal\x18\x03 \x01(\tR\boriginal\x12 \n" +
	"\vtranslation\x18\x04 \x01(\tR\vtranslation2T\n" +
	"\vTranslation\x12E\n" +
	"\n" +
	"GetHistory\x12\x1a.grpc.v1.GetHistoryRequest\x1a\x1b.grpc.v1.GetHistoryResponseB\x0fZ\rdocs/proto/v1b\x06proto3"

var (
	file_docs_proto_v1_translation_history_proto_rawDescOnce sync.Once
	file_docs_proto_v1_translation_history_proto_rawDescData []byte
)

func file_docs_proto_v1_translation_history_proto_rawDescGZIP() []byte {
	file_docs_proto_v1_translation_history_proto_rawDescOnce.Do(func() {
		file_docs_proto_v1_translation_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docs_proto_v1_translation_history_proto_rawDesc), len(file_docs_proto_v1_translation_history_proto_rawDesc)))
	})
	return file_docs_proto_v1_translation_history_proto_rawDescData
}

var file_docs_proto_v1_translation_history_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_docs_proto_v1_translation_history_proto_goTypes = []any{
	(*GetHistoryRequest)(nil),  // 0: grpc.v1.GetHistoryRequest
	(*GetHistoryResponse)(nil), // 1: grpc.v1.GetHistoryResponse
	(*TranslationHistory)(nil), // 2: grpc.v1.TranslationHistory
}
var file_docs_proto_v1_translation_history_proto_depIdxs = []int32{
	2, // 0: grpc.v1.GetHistoryResponse.history:type_name -> grpc.v1.TranslationHistory
	0, // 1: grpc.v1.Translation.GetHistory:input_type -> grpc.v1.GetHistoryRequest
	1, // 2: grpc.v1.Translation.GetHistory:output_type -> grpc.v1.GetHistoryResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_docs_proto_v1_translation_history_proto_init() }
func file_docs_proto_v1_translation_history_proto_init() {
	if File_docs_proto_v1_translation_history_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docs_proto_v1_translation_history_proto_rawDesc), len(file_docs_proto_v1_translation_history_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docs_proto_v1_translation_history_proto_goTypes,
		DependencyIndexes: file_docs_proto_v1_translation_history_proto_depIdxs,
		MessageInfos:      file_docs_proto_v1_translation_history_proto_msgTypes,
	}.Build()
	File_docs_proto_v1_translation_history_proto = out.File
	file_docs_proto_v1_translation_history_proto_goTypes = nil
	file_docs_proto_v1_translation_history_proto_depIdxs = nil
}
