// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EntityUseCase is an autogenerated mock type for the EntityUseCase type
type EntityUseCase struct {
	mock.Mock
}

// DoTranslate provides a mock function with given fields:
func (_m *EntityUseCase) DoTranslate() {
	_m.Called()
}
