// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/evrone/go-service-template/domain"
	mock "github.com/stretchr/testify/mock"
)

// EntityUseCase is an autogenerated mock type for the EntityUseCase type
type EntityUseCase struct {
	mock.Mock
}

// Do provides a mock function with given fields: ctx, entity
func (_m *EntityUseCase) Do(ctx context.Context, entity domain.Entity) error {
	ret := _m.Called(ctx, entity)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Entity) error); ok {
		r0 = rf(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
