// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import (
	domain "github.com/evrone/go-service-template/business-logic/domain"
	mock "github.com/stretchr/testify/mock"
)

// EntityTranslator is an autogenerated mock type for the EntityTranslator type
type EntityTranslator struct {
	mock.Mock
}

// Translate provides a mock function with given fields: _a0
func (_m *EntityTranslator) Translate(_a0 domain.Entity) (domain.Entity, error) {
	ret := _m.Called(_a0)

	var r0 domain.Entity
	if rf, ok := ret.Get(0).(func(domain.Entity) domain.Entity); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(domain.Entity)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.Entity) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
