// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/evrone/go-service-template/domain"
	mock "github.com/stretchr/testify/mock"
)

// EntityRepository is an autogenerated mock type for the EntityRepository type
type EntityRepository struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, entity
func (_m *EntityRepository) Get(ctx context.Context, entity domain.Entity) (domain.Entity, error) {
	ret := _m.Called(ctx, entity)

	var r0 domain.Entity
	if rf, ok := ret.Get(0).(func(context.Context, domain.Entity) domain.Entity); ok {
		r0 = rf(ctx, entity)
	} else {
		r0 = ret.Get(0).(domain.Entity)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.Entity) error); ok {
		r1 = rf(ctx, entity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
