// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repo/contracts.go

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"

	entity "github.com/evrone/todo-svc/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockTodoRepo is a mock of TodoRepo interface.
type MockTodoRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTodoRepoMockRecorder
	isgomock struct{}
}

// MockTodoRepoMockRecorder is the mock recorder for MockTodoRepo.
type MockTodoRepoMockRecorder struct {
	mock *MockTodoRepo
}

// NewMockTodoRepo creates a new mock instance.
func NewMockTodoRepo(ctrl *gomock.Controller) *MockTodoRepo {
	mock := &MockTodoRepo{ctrl: ctrl}
	mock.recorder = &MockTodoRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoRepo) EXPECT() *MockTodoRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTodoRepo) Create(arg0 context.Context, arg1 entity.Todo) (entity.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(entity.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTodoRepoMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTodoRepo)(nil).Create), arg0, arg1)
}

// GetByID mocks base method.
func (m *MockTodoRepo) GetByID(arg0 context.Context, arg1 int) (entity.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(entity.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTodoRepoMockRecorder) GetByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTodoRepo)(nil).GetByID), arg0, arg1)
}

// List mocks base method.
func (m *MockTodoRepo) List(arg0 context.Context) ([]entity.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].([]entity.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTodoRepoMockRecorder) List(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTodoRepo)(nil).List), arg0)
}

// Update mocks base method.
func (m *MockTodoRepo) Update(arg0 context.Context, arg1 int, arg2 entity.Todo) (entity.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(entity.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTodoRepoMockRecorder) Update(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTodoRepo)(nil).Update), arg0, arg1, arg2)
}

// Delete mocks base method.
func (m *MockTodoRepo) Delete(arg0 context.Context, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTodoRepoMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTodoRepo)(nil).Delete), arg0, arg1)
}
